resolution = 0.125

[poisson]
lib = "singular.lua"
boundary = "solution"
coefficient = "coefficient"
solution = "solution"
solution_jacobian = "solution_jacobian"

[generate_mesh]
intercepts = [
    [-1, 1],
    [-1, 1]
]
bcs = [
    [{bc = "d", plane = 0}, {bc = "d", plane = 1}],
    [{bc = "d", plane = 0}, {bc = "d", plane = 1}]
]

