mesh_file = "dip.msh"

[elasticity]
lib = "dip.lua"
boundary = "solution"
slip = "slip"
solution = "solution"
solution_jacobian = "solution_jacobian"
mu = "mat_mu"
lam = "mat_lam"
ref_normal = [1, 0]
