final_time = 47304000000
mesh_file = "bp1_sym.msh"
mode = "QDGreen"
type = "poisson"
lib = "bp1.lua"
scenario = "bp1_sym"
ref_normal = [-1, 0]
boundary_linear = true

[fault_probe_output]
prefix = "fltst_"
t_max = 9460800 # Maximum output 
probes = [
    { name = "dp000", x = [0.0, 0.0] },
    { name = "dp005", x = [0.0, -0.5] },
    { name = "dp010", x = [0.0, -1.0] },
    { name = "dp015", x = [0.0, -1.5] },
    { name = "dp020", x = [0.0, -2.0] },
    { name = "dp025", x = [0.0, -2.5] },
    { name = "dp030", x = [0.0, -3.0] },
    { name = "dp035", x = [0.0, -3.5] },
    { name = "dp040", x = [0.0, -4.0] },
    { name = "dp045", x = [0.0, -4.5] },
    { name = "dp050", x = [0.0, -5.0] },
    { name = "dp055", x = [0.0, -5.5] },
    { name = "dp060", x = [0.0, -6.0] },
    { name = "dp065", x = [0.0, -6.5] },
    { name = "dp070", x = [0.0, -7.0] },
    { name = "dp075", x = [0.0, -7.5] },
    { name = "dp080", x = [0.0, -8.0] },
    { name = "dp085", x = [0.0, -8.5] },
    { name = "dp090", x = [0.0, -9.0] },
    { name = "dp095", x = [0.0, -9.5] },
    { name = "dp100", x = [0.0, -10.0] },
    { name = "dp105", x = [0.0, -10.5] },
    { name = "dp110", x = [0.0, -11.0] },
    { name = "dp115", x = [0.0, -11.5] },
    { name = "dp120", x = [0.0, -12.0] },
    { name = "dp125", x = [0.0, -12.5] },
    { name = "dp130", x = [0.0, -13.0] },
    { name = "dp135", x = [0.0, -13.5] },
    { name = "dp140", x = [0.0, -14.0] },
    { name = "dp145", x = [0.0, -14.5] },
    { name = "dp150", x = [0.0, -15.0] },
    { name = "dp155", x = [0.0, -15.5] },
    { name = "dp160", x = [0.0, -16.0] },
    { name = "dp165", x = [0.0, -16.5] },
    { name = "dp170", x = [0.0, -17.0] },
    { name = "dp175", x = [0.0, -17.5] },
    { name = "dp180", x = [0.0, -18.0] },
    { name = "dp195", x = [0.0, -19.5] },
    { name = "dp210", x = [0.0, -21.0] },
    { name = "dp225", x = [0.0, -22.5] },
    { name = "dp240", x = [0.0, -24.0] },
    { name = "dp255", x = [0.0, -25.5] },
    { name = "dp275", x = [0.0, -27.5] },
    { name = "dp295", x = [0.0, -29.5] },
    { name = "dp315", x = [0.0, -31.5] },
    { name = "dp335", x = [0.0, -33.5] },
    { name = "dp355", x = [0.0, -35.5] },
    { name = "dp375", x = [0.0, -37.5] },
    { name = "dp395", x = [0.0, -39.5] }
]
