final_time = 12.0
mesh_file = "tpv102.msh"
lib = "tpv102.lua"
scenario = "tpv102"
mode = "FD"
type = "elasticity"
ref_normal = [0, -1, 0]
boundary_linear = true

[fault_probe_output]
prefix = "fltst_"
rtol = 1
t_max = 0.001
probes = [
    { name = "strk-12dp+030", x = [-12, 0,  -3] },
    { name = "strk+00dp+030", x = [  0, 0,  -3] },
    { name = "strk+12dp+030", x = [ 12, 0,  -3] },
    { name = "strk-09dp+075", x = [ -9, 0,-7.5] },
    { name = "strk+00dp+075", x = [  0, 0,-7.5] },
    { name = "strk+09dp+075", x = [  9, 0,-7.5] },
    { name = "strk-12dp+120", x = [-12, 0, -12] },
    { name = "strk+00dp+120", x = [  0, 0, -12] },
    { name = "strk+12dp+120", x = [ 12, 0, -12] }
]

[domain_probe_output]
prefix = "blkst_"
rtol = 1
t_max = 0.001
probes = [
    { name = "strk-12fn-6", x = [-12, -6, 0] },
    { name = "strk+00fn-9", x = [  0, -9, 0] },
    { name = "strk+12fn-6", x = [ 12, -6, 0] },
    { name = "strk-12fn+6", x = [-12,  6, 0] },
    { name = "strk+00fn+9", x = [  0,  9, 0] },
    { name = "strk+12fn+6", x = [ 12,  6, 0] }
]
