final_time = 1e7
mesh_file = "bp1_sym.msh"
mode = "QDGreen"
type = "poisson"
lib = "bp1.lua"
scenario = "bp1_sym"
ref_normal = [-1, 0]
boundary_linear = true

gf_checkpoint_prefix = "/export/dump/jyun/GreensFunctions/bp1_sym_hf02"

[fault_output]
prefix = "fault/fault_"
rtol = 0.1