final_time = 0
mesh_file = "ridgecrest_hf25.msh"
mode = "QDGreen"
type = "poisson"
lib = "matfric_Fourier_main_reference.lua"
scenario = "bp1_sym"
ref_normal = [-1, 0]
boundary_linear = true

gf_checkpoint_prefix = "/hppfs/scratch/06/di75weg/GreensFunctions/depth_dep_sn/ridgecrest_hf25"
