final_time = 1460000
mesh_file = "ridgecrest_hf05.msh"
mode = "QDGreen"
type = "poisson"
lib = "matfric_Fourier_main_reference.lua"
scenario = "bp1_sym"
ref_normal = [-1, 0]
boundary_linear = true

gf_checkpoint_prefix = "/hppfs/scratch/06/di75weg/GreensFunctions/depth_dep_sn/ridgecrest_hf05"

[fault_probe_output]
prefix = "faultp_"
t_max = 9460800
probes = [
    { name = "fp100", x = [0.0, -10.0000] }
]
