final_time = 0
mesh_file = "ridgecrest_hf10.msh"
mode = "QDGreen"
type = "poisson"
lib = "matfric_Fourier_main_reference.lua"
scenario = "bp1_sym"
ref_normal = [-1, 0]
boundary_linear = true

gf_checkpoint_prefix = "/export/dump/jyun/GreensFunctions/ridgecrest_hf10"