final_time = 157680000000
mesh_file = "ridgecrest_hf125.msh"
mode = "QDGreen"
type = "poisson"
lib = "scenario_perturb.lua"
scenario = "vs340_64467_lowres_spinup_aginglaw_reference"
ref_normal = [-1, 0]
boundary_linear = true

gf_checkpoint_prefix = "/export/dump/jyun/GreensFunctions/ridgecrest_hf125"

[fault_probe_output]
prefix = "faultp_"
t_max = 0.009
probes = [
    { name = "fp222", x = [0.0, -4.4400] }
]