final_time = 31536000
mesh_file = "ridgecrest_hf25.msh"
mode = "QDGreen"
type = "poisson"
lib = "matfric_Fourier_main_reference_slowVpl.lua"
scenario = "bp1_sym"
ref_normal = [-1, 0]
boundary_linear = true

gf_checkpoint_prefix = "/export/dump/jyun/GreensFunctions/ridgecrest_hf25"

[domain_probe_output]
prefix = "domainp_"
t_max = 9460800
probes = [
    { name = "dp000", x = [0.0, 0.0] },
    { name = "dp001", x = [50.0, 0.0] },
    { name = "dp002", x = [100.0, 0.0] },
    { name = "dp003", x = [150.0, 0.0] },
    { name = "dp004", x = [200.0, 0.0] },
    { name = "dp005", x = [250.0, 0.0] },
    { name = "dp006", x = [300.0, 0.0] },
    { name = "dp007", x = [350.0, 0.0] },
    { name = "dp008", x = [400.0, 0.0] },
    { name = "dp009", x = [0.0, -25.0] },
    { name = "dp010", x = [0.0, -50.0] },
    { name = "dp011", x = [0.0, -100.0] },
    { name = "dp012", x = [0.0, -150.0] },
    { name = "dp013", x = [0.0, -200.0] },
    { name = "dp014", x = [0.0, -250.0] },
    { name = "dp015", x = [0.0, -300.0] },
    { name = "dp016", x = [0.0, -350.0] },
    { name = "dp017", x = [0.0, -400.0] },
    { name = "dp018", x = [0.0, -5.0] },
    { name = "dp019", x = [0.0, -10.0] },
    { name = "dp020", x = [0.0, -15.0] },
    { name = "dp021", x = [0.0, -20.0] },
    { name = "dp022", x = [0.0, -24.0] },
    { name = "dp023", x = [0.0, -24.2] },
    { name = "dp024", x = [0.0, -24.4] },
    { name = "dp025", x = [0.0, -24.6] },
    { name = "dp026", x = [0.0, -24.8] }
]